In [14]:
import numpy as np
A = np.array([[1, 2, 1, -3],
             [3, 3, -2, 2],
             [2, -1, -3, 1],
             [4, 4, -1, -1]])

B = np.linalg.inv(A)
C = np.dot(B, A)

D = np.array([[-16], [7], [-1], [-7]])

E = np.dot(B, D)

print(f"{A}\n\n{B}\n\n{C}\n\n{D}\n\n{E}")

[[ 1  2  1 -3]
 [ 3  3 -2  2]
 [ 2 -1 -3  1]
 [ 4  4 -1 -1]]

[[-1.6  -1.4  -0.2   1.8 ]
 [ 1.    1.   -0.   -1.  ]
 [-1.65 -1.35 -0.55  1.7 ]
 [-0.75 -0.25 -0.25  0.5 ]]

[[ 1.00000000e+00  8.88178420e-16 -2.22044605e-16  8.88178420e-16]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-8.88178420e-16 -8.88178420e-16  1.00000000e+00 -8.88178420e-16]
 [ 0.00000000e+00  0.00000000e+00  1.11022302e-16  1.00000000e+00]]

[[-16]
 [  7]
 [ -1]
 [ -7]]

[[ 3.4]
 [-2. ]
 [ 5.6]
 [ 7. ]]
